### ISSUE TITLE
Update to support current API functionality

### ISSUE THREAD

**Issue by KDercksen** [clean-cloogle/cloogle-cli#13]
There are more supported fields that need to be implemented. I'll update this issue as I make up for lost maintenance work...

- [x] Switch to HTTP API
- [x] className
- [x] typeName
- [x] libraries
- [x] include_builtins
- [x] include_core

**Comment by camilstaps** [comment]
Access to the HTTP API is limited, you will hit DOS protection when using more than 3 requests per second. The TCP API does not have this limitation. (Perhaps the DOS protection can be lifted if the request is the same safe for the page number, but that would have to be implemented first.)

On the other hand, if you decide to use the HTTP API, it would be nice to choose a custom user agent and add it [here](https://github.com/clean-cloogle/cloogle/blob/master/frontend/stats/ajax/oss.php#L19) to get usage statistics. (This is not possible with the TCP API.)
