### ISSUE TITLE
Implement usage statistics

### ISSUE THREAD

**Issue by KDercksen** [clean-cloogle/cloogle-cli#14]
This'll need some coordination with the Cloogle maintainers, i.e. choosing a user agent as mentioned in #13

**Comment by camilstaps** [comment]
We don't have any naming guidelines. Other user agents are `vim-clean`, `CloogleBot` and `CloogleMail` (not yet in oss.php but see https://github.com/clean-cloogle/cloogle-mail/blob/master/cloogle_mail.py), so I would suggest `cloogle-cli` or perhaps `CloogleCLI`.

**Comment by KDercksen** [comment]
@camilstaps I went with `cloogle-cli`!

**Comment by camilstaps** [comment]
Great, has been added to https://github.com/clean-cloogle/cloogle/commit/976ad47282e0db62d309a400539f72d73eb4d22a.
