### ISSUE TITLE
Support the new include Apps flag

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle-cli#15]
The following commit added it as a search option:
https://github.com/clean-cloogle/cloogle.org/commit/3b5eeb8effe290294b2db8b4619352e48336bc12

**Comment by camilstaps** [comment]
https://github.com/clean-cloogle/libcloogle/commit/9774125cdd65ff59f2249f4553818cc7a92905d6 is the commit in the API repo (which looks less daunting).
